### ISSUE TITLE
[SLF4J] Failed to load class "org.slf4j.impl.StaticLoggerBinder". Defaulting to no-operation (NOP) logger implementation

### ISSUE THREAD

**Issue by aohontsev** [eroshenkoam/allure-testops-utils#20]
Hello there!

We have some issue with running allure-testops-utils sync-ldap-groups
It's seems that this hsould help with fixing https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder/9919375#9919375

```
allure-testops-utils sync-ldap-groups
Prepare to sync [aadolzhnikov, aaklimov, aamardonov, aaohontsev, aasokolov, aatseplyaev, aazaytsev, admin, adstuchinskiy, akartamonov] users from Allure
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Found information about [sgAllure_CP_owner, sgAllure_CP_write, sgAllure_SITE_owner, sgAllure_DOC_owner, sgAllure_CPI_read, sgAllure_AICE_read, sgAllure_AICD_write, sgAllure_SITE_read, sgAllure_SITE_write, sgAllure_CP_read, sgAllure_QA, sgAllure_SBDB2B_write, sgAllure_AICDC_write, sgAllure_DOC_read, sgAllure_SBD_write, sgAllure_AICDC_read, sgAllure_AICE_owner, sgAllure_DOC_write, sgAllure_AICW_owner, sgAllure_ADV_owner, sgAllure_ADV_read, sgAllure_CPC_write, sgAllure_SDBUSINESS_write, 
sgAllure_admins, sgAllure_ADV_write, sgAllure_KBR_owner, sgAllure_LT_owner, sgAllure_AICE_write, sgAllure_CPI_write, sgAllure_KBR_write, sgAllure_SBDB2B_read, sgAllure_SBD_read, sgAllure_SDBUSINESS_owner, sgAllure_SDBUSINESS_read, sgAllure_CPI_owner, sgAllure_AICD_owner, sgAllure_SBDB2B_owner, sgAllure_users, sgAllure_AICW_read, sgAllure_AICW_write, sgAllure_CPC_owner, sgAllure_KBR_read, sgAllure_CPC_read, sgAllure_AICD_read, sgAllure_AICDC_owner, sgAllure_SBD_owner] in Crowd
java.lang.RuntimeException: 
        at io.github.eroshenkoam.allure.command.AbstractSyncGroupsCommand.syncAllureGroups(AbstractSyncGroupsCommand.java:42)
        at io.github.eroshenkoam.allure.command.AbstractSyncGroupsCommand.runUnsafe(AbstractSyncGroupsCommand.java:34)
        at io.github.eroshenkoam.allure.command.AbstractTestOpsCommand.run(AbstractTestOpsCommand.java:35)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at io.github.eroshenkoam.allure.AllureTestOpsUtils.main(AllureTestOpsUtils.java:13)
```

**Comment by Elvintest** [comment]
Up the issue
