### ISSUE TITLE
crowd groups sync does not work with the Allure TestOps release 4.+

### ISSUE THREAD

**Issue by cheshi-mantu** [eroshenkoam/allure-testops-utils#23]
The tool crashes with the following exception

```
Prepare to sync [20007177, 20009453, 20014144, 20015103, 20101744, 20102203, 60000909, 60001240, 60001792, 60002465] users from Allure
Found information about [crowd-triffle-microfronts, crowd-sentry-users, crowd-triffle, crowd-hyperion, crowd-hyperion-admin, crowd-lm-ad-auth-complete, crowd-triffle-ro, crowd-devportal-users-ro, crowd-ldap-server-users, crowd-triffle-microfronts-admin, crowd-ldap-server-github-users] in Crowd
java.lang.RuntimeException:
	at io.github.eroshenkoam.allure.command.AbstractSyncGroupsCommand.syncAllureGroups(AbstractSyncGroupsCommand.java:77)
	at io.github.eroshenkoam.allure.command.AbstractSyncGroupsCommand.runUnsafe(AbstractSyncGroupsCommand.java:69)
	at io.github.eroshenkoam.allure.command.AbstractSyncGroupsCommand.run(AbstractSyncGroupsCommand.java:48)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at io.github.eroshenkoam.allure.AllureTestOpsUtils.main(AllureTestOpsUtils.java:13)

```

**Comment by eroshenkoam** [comment]
fixed
