### ISSUE TITLE
to add launches cleaner to the repository allure-testops-utils

### ISSUE THREAD

**Issue by cheshi-mantu** [eroshenkoam/allure-testops-utils#8]
https://help.qameta.io/a/tickets/329
Problem with launch cleaner by using allure-ee-client.
It's important for us
(uncleaned lunches lead to an increase in the size of the database and difficulties in operations)
Allure version: 3.193.0

build.gradle.kts:
```Kotlin
  maven("[https://dl.qameta.io/artifactory/maven"](https://dl.qameta.io/artifactory/maven))
  implementation("io.qameta.allure:allure-ee-client:3.40.3")

```
Main: 
```java
public static void main(final String[] args) throws Exception {
    final ServerApi serverApi = builder.create(ServerApi.class);
    final LaunchService launchService = builder.create(LaunchService.class);

    List<Project> projects = serverApi.listProjects().execute().body();
    assert projects != null;
    for (Project project : projects) {
        final Page<Launch> launches = launchService
            .findAll(project.getId(), LAUNCH_FILTER, 0, 2000)
            .execute().body();
        assert launches != null;
        for (final Launch launch : launches.getContent()) {
            launchService.delete(launch.getId()).execute();
            System.out.printf("Delete launch %s for id: %s%n", launch.getId(), project.getId());
        }
    }
}
```
Stack trace:
```shell
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<io.qameta.allure.ee.client.dto.Project>` out of START_OBJECT token
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 1]
 at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
 at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
 at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
 at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
 at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
 at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
 at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
 at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
 at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
 at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
 at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
 at io.github.eroshenkoam.allure.LaunchCleaner.main(LaunchCleaner.java:26)
```

**Comment by eroshenkoam** [comment]
https://github.com/eroshenkoam/allure-testops-utils/releases/tag/1.5
